"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { CheckCircle2,FileUp,ShieldCheck,Trash2 } from "lucide-react";
import { childrenApi } from "@/lib/children";
import { apiErrorMessage } from "@/lib/api";
import { usePermissions } from "@/hooks/usePermissions";
import type { AdmissionChecklistItem,AdmissionDocumentType,ChildDocument } from "@/types/children";

export function ChildDocumentsPanel({childId}:{childId:number}){
 const {hasAnyRole,isAdmin,isViewer}=usePermissions();const canWrite=hasAnyRole(["Admin","Manager","Data Entry Operator"]);const [documents,setDocuments]=useState<ChildDocument[]>([]);const [types,setTypes]=useState<AdmissionDocumentType[]>([]);const [checklist,setChecklist]=useState<AdmissionChecklistItem[]>([]);const [type,setType]=useState("");const [file,setFile]=useState<File|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [docs,definitions,items]=await Promise.all([childrenApi.documents(childId),childrenApi.documentTypes(),childrenApi.documentChecklist(childId)]);setDocuments(docs);setTypes(definitions);setChecklist(items);setType(current=>current||definitions[0]?.document_type||"")}catch(e){setError(apiErrorMessage(e))}finally{setLoading(false)}},[childId]);useEffect(()=>{void load()},[load]);
 const required=checklist.filter(item=>item.required);const uploaded=required.filter(item=>item.uploaded).length;const verified=required.filter(item=>item.verified).length;const complete=required.length>0&&verified===required.length;const selected=types.find(item=>item.document_type===type);const accept=useMemo(()=>selected?.extensions.map(ext=>`.${ext}`).join(",")||".pdf,.jpg,.jpeg,.png",[selected]);
 const upload=async()=>{if(!file||!type)return;setBusy(true);setError("");try{await childrenApi.uploadDocument(childId,type,file);setFile(null);await load()}catch(e){setError(apiErrorMessage(e))}finally{setBusy(false)}};const verify=async(id:number)=>{setBusy(true);try{await childrenApi.verifyDocument(id);await load()}catch(e){setError(apiErrorMessage(e))}finally{setBusy(false)}};const remove=async(id:number)=>{if(!confirm("Delete this document?"))return;setBusy(true);try{await childrenApi.deleteDocument(id);await load()}catch(e){setError(apiErrorMessage(e))}finally{setBusy(false)}};
 return <section className="panel"><div className="panel-title"><div><h2>Admission documents</h2><p className="mt-1 text-sm text-slate-500">Required uploaded: {uploaded} of {required.length} · verified: {verified} of {required.length} · complete: {complete?"Yes":"No"}</p></div><span className={complete?"badge-success":"badge"}>{complete?"Complete":"Incomplete"}</span></div>{!complete&&<div className="notice-warning mb-5">Admission file is incomplete until all required documents are uploaded and verified.</div>}{error&&<div className="notice-error mb-4">{error}</div>}{loading?<p className="text-sm text-slate-500">Loading document checklist…</p>:<div className="mb-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{checklist.map(item=><div className="rounded-lg border border-slate-200 p-3" key={item.document_type}><div className="flex items-start justify-between gap-2"><p className="text-sm font-semibold">{item.document_type}</p><span className={item.verified?"badge-success":item.uploaded?"badge-warning":"badge"}>{item.status}</span></div><p className="mt-1 text-xs text-slate-500">{item.required?"Required":"Optional"}{item.uploaded_count?` · ${item.uploaded_count} uploaded`:""}</p></div>)}</div>}{canWrite&&<div className="mb-5 grid gap-3 rounded-xl bg-slate-50 p-4 md:grid-cols-[1fr_1fr_auto]"><select className="field-control" value={type} onChange={e=>setType(e.target.value)}>{types.map(item=><option value={item.document_type} key={item.document_type}>{item.document_type} {item.required?"(Required)":"(Optional)"}</option>)}</select><input className="field-control" type="file" accept={accept} onChange={e=>setFile(e.target.files?.[0]||null)}/><button disabled={!file||busy} onClick={upload} className="primary-button"><FileUp size={16}/>Upload</button></div>}{documents.length?<div className="space-y-2">{documents.map(doc=><div key={doc.id} className="flex flex-col gap-3 rounded-lg border border-slate-200 p-3 sm:flex-row sm:items-center"><div className="flex-1"><p className="font-medium">{doc.document_type}</p>{!isViewer()&&<p className="text-xs text-slate-500">{doc.original_filename}</p>}</div><span className={doc.is_verified?"badge-success":"badge"}>{doc.is_verified?"Verified":"Pending verification"}</span>{canWrite&&!doc.is_verified&&<button disabled={busy} className="icon-button" title="Verify" onClick={()=>verify(doc.id)}><ShieldCheck size={17}/></button>}{isAdmin()&&<button disabled={busy} className="icon-button text-red-600" title="Delete" onClick={()=>remove(doc.id)}><Trash2 size={17}/></button>}</div>)}</div>:!loading&&<div className="empty-inline"><CheckCircle2/><span>No admission documents uploaded yet.</span></div>}</section>;
}
