"use client";
import { useState } from "react";import { useRouter } from "next/navigation";import { useForm } from "react-hook-form";import { apiErrorMessage } from "@/lib/api";import { childrenApi } from "@/lib/children";import type { Child,ChildCreatePayload,ChildUpdatePayload } from "@/types/children";
const fields:[keyof ChildCreatePayload,string,string][]=[
 ["child_id","Child ID","text"],["admission_file_no","Admission file number","text"],["full_name","Full name","text"],["father_name","Father name","text"],["grandfather_name","Grandfather name","text"],["mother_name","Mother name","text"],["date_of_birth","Date of birth","date"],["guardian_name","Guardian name","text"],["guardian_relationship","Guardian relationship","text"],["guardian_cnic","Guardian CNIC / passport","text"],["guardian_mobile","Guardian mobile","tel"],["current_address","Current address","textarea"],["permanent_address","Permanent address","textarea"],["village_mohallah","Village / Mohallah","text"],["union_council","Union council","text"],["tehsil","Tehsil","text"],["district","District","text"],["province","Province","text"],["admission_date","Admission date","date"],["reason_for_admission","Reason for admission","textarea"]];
const immutable=new Set<keyof ChildCreatePayload>(["child_id","admission_file_no","gender","date_of_birth","admission_date"]);
export function ChildForm({child}:{child?:Child}){const edit=Boolean(child);const router=useRouter();const [error,setError]=useState("");const [success,setSuccess]=useState("");const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<ChildCreatePayload>({defaultValues:child});
 const submit=async(values:ChildCreatePayload)=>{setError("");setSuccess("");try{let saved:Child;if(edit){const payload=Object.fromEntries(Object.entries(values).filter(([key])=>!immutable.has(key as keyof ChildCreatePayload))) as ChildUpdatePayload;saved=await childrenApi.update(child!.id,payload)}else saved=await childrenApi.create(values);setSuccess(edit?"Child record updated successfully.":"Child record created successfully.");setTimeout(()=>router.push(`/dashboard/children/${saved.id}`),500)}catch(e){setError(apiErrorMessage(e))}};
 return <form onSubmit={handleSubmit(submit)} className="space-y-7"><Notice error={error} success={success}/><FormSection title="Identification and child information"><div className="form-grid">{fields.slice(0,7).map(field=><Field key={field[0]} spec={field} register={register} error={errors[field[0]]?.message as string|undefined} disabled={edit&&immutable.has(field[0])}/>)}<SelectField label="Gender" disabled={edit} registration={register("gender",{required:"Gender is required"})} error={errors.gender?.message} options={["Male","Female","Other"]}/></div></FormSection><FormSection title="Guardian information"><div className="form-grid">{fields.slice(7,11).map(field=><Field key={field[0]} spec={field} register={register} error={errors[field[0]]?.message as string|undefined}/>)}</div></FormSection><FormSection title="Address information"><div className="form-grid">{fields.slice(11,18).map(field=><Field key={field[0]} spec={field} register={register} error={errors[field[0]]?.message as string|undefined}/>)}</div></FormSection><FormSection title="Admission information"><div className="form-grid">{fields.slice(18).map(field=><Field key={field[0]} spec={field} register={register} error={errors[field[0]]?.message as string|undefined} disabled={edit&&immutable.has(field[0])}/>) }<SelectField label="Status" registration={register("status",{required:"Status is required"})} error={errors.status?.message} options={["Active","Inactive","Discharged","Transferred"]}/></div></FormSection><div className="flex justify-end gap-3"><button type="button" onClick={()=>router.back()} className="secondary-button">Cancel</button><button disabled={isSubmitting} className="primary-button">{isSubmitting?"Saving…":edit?"Save changes":"Create child"}</button></div></form>}
function FormSection({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><h2 className="mb-5 text-lg font-bold">{title}</h2>{children}</section>}
function Field({spec,register,error,disabled=false}:{spec:[keyof ChildCreatePayload,string,string];register:ReturnType<typeof useForm<ChildCreatePayload>>["register"];error?:string;disabled?:boolean}){const [name,label,type]=spec;const props=register(name,{required:`${label} is required`});return <label className={type==="textarea"?"form-field md:col-span-2":"form-field"}><span>{label}</span>{type==="textarea"?<textarea rows={3} disabled={disabled} {...props}/>:<input type={type} disabled={disabled} {...props}/>} {error&&<small>{error}</small>}</label>}
function SelectField({label,registration,error,options,disabled=false}:{label:string;registration:ReturnType<ReturnType<typeof useForm<ChildCreatePayload>>["register"]>;error?:string;options:string[];disabled?:boolean}){return <label className="form-field"><span>{label}</span><select disabled={disabled} {...registration}><option value="">Select {label.toLowerCase()}</option>{options.map(option=><option key={option}>{option}</option>)}</select>{error&&<small>{error}</small>}</label>}
function Notice({error,success}:{error:string;success:string}){return <>{error&&<div className="notice-error">{error}</div>}{success&&<div className="notice-success">{success}</div>}</>}
