from datetime import UTC, date, datetime, time
from sqlalchemy import Boolean, CheckConstraint, Date, DateTime, ForeignKey, Index, String, Text, Time
from sqlalchemy.orm import Mapped, mapped_column
from app.core.database import Base

def now():return datetime.now(UTC)

class Visitor(Base):
    __tablename__="visitors"
    __table_args__=(CheckConstraint("status IN ('Active','Inactive','Blocked','Pending Verification')",name="ck_visitors_status"),Index("ix_visitors_status_verified","status","is_verified"),)
    id:Mapped[int]=mapped_column(primary_key=True);visitor_code:Mapped[str]=mapped_column(String(50),unique=True,index=True);full_name:Mapped[str]=mapped_column(String(255),index=True);father_name:Mapped[str|None]=mapped_column(String(255),nullable=True);cnic_passport:Mapped[str|None]=mapped_column(String(50),nullable=True);mobile:Mapped[str|None]=mapped_column(String(30),nullable=True);alternate_mobile:Mapped[str|None]=mapped_column(String(30),nullable=True);relationship_to_child:Mapped[str]=mapped_column(String(100));address:Mapped[str|None]=mapped_column(Text,nullable=True);district:Mapped[str|None]=mapped_column(String(100),nullable=True,index=True);province:Mapped[str|None]=mapped_column(String(100),nullable=True);photo_path:Mapped[str|None]=mapped_column(Text,nullable=True);is_verified:Mapped[bool]=mapped_column(Boolean,default=False);verification_method:Mapped[str|None]=mapped_column(String(100),nullable=True);verified_by_user_id:Mapped[int|None]=mapped_column(ForeignKey("users.id"),nullable=True);verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True);status:Mapped[str]=mapped_column(String(30),default="Pending Verification");remarks:Mapped[str|None]=mapped_column(Text,nullable=True);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now);created_by_user_id:Mapped[int]=mapped_column(ForeignKey("users.id"));updated_by_user_id:Mapped[int]=mapped_column(ForeignKey("users.id"));deleted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True);deleted_by_user_id:Mapped[int|None]=mapped_column(ForeignKey("users.id"),nullable=True)

class ChildVisit(Base):
    __tablename__="child_visits"
    __table_args__=(CheckConstraint("approval_status IN ('Pending','Approved','Rejected','Cancelled')",name="ck_child_visits_approval"),CheckConstraint("visit_status IN ('Scheduled','Checked In','Completed','No Show','Cancelled')",name="ck_child_visits_status"),CheckConstraint("check_out_time IS NULL OR check_in_time IS NULL OR check_out_time >= check_in_time",name="ck_child_visits_times"),Index("ix_child_visits_date_status","visit_date","visit_status"),)
    id:Mapped[int]=mapped_column(primary_key=True);visit_code:Mapped[str]=mapped_column(String(50),unique=True,index=True);child_id:Mapped[int]=mapped_column(ForeignKey("children.id",ondelete="RESTRICT"),index=True);visitor_id:Mapped[int]=mapped_column(ForeignKey("visitors.id",ondelete="RESTRICT"),index=True);relationship_to_child:Mapped[str]=mapped_column(String(100));visit_date:Mapped[date]=mapped_column(Date,index=True);check_in_time:Mapped[time|None]=mapped_column(Time,nullable=True);check_out_time:Mapped[time|None]=mapped_column(Time,nullable=True);meeting_purpose:Mapped[str]=mapped_column(String(100));meeting_location:Mapped[str]=mapped_column(String(100));supervised_by_user_id:Mapped[int|None]=mapped_column(ForeignKey("users.id"),nullable=True);approved_by_user_id:Mapped[int|None]=mapped_column(ForeignKey("users.id"),nullable=True);approval_status:Mapped[str]=mapped_column(String(20),default="Pending");visit_status:Mapped[str]=mapped_column(String(20),default="Scheduled");remarks:Mapped[str|None]=mapped_column(Text,nullable=True);safety_notes:Mapped[str|None]=mapped_column(Text,nullable=True);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now);created_by_user_id:Mapped[int]=mapped_column(ForeignKey("users.id"));updated_by_user_id:Mapped[int]=mapped_column(ForeignKey("users.id"))
