"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {api,apiErrorMessage} from "@/lib/api";
import {visitorsApi} from "@/lib/visitors";
import type {Permission,Role} from "@/types/visitors";

export default function RolesPage(){
 const [roles,setRoles]=useState<Role[]>([]),[permissions,setPermissions]=useState<Permission[]>([]),[roleId,setRoleId]=useState(0),[selected,setSelected]=useState<Set<number>>(new Set()),[name,setName]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
 const role=roles.find(item=>item.id===roleId);
 const load=useCallback(async()=>{setLoading(true);try{const [roleRows,permissionRows]=await Promise.all([visitorsApi.roles(),visitorsApi.permissions()]);setRoles(roleRows);setPermissions(permissionRows);setRoleId(current=>current||roleRows[0]?.id||0)}catch(e){setError(apiErrorMessage(e))}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(roleId)visitorsApi.rolePermissions(roleId).then(rows=>setSelected(new Set(rows.map(item=>item.id)))).catch(e=>setError(apiErrorMessage(e)))},[roleId]);
 const groups=useMemo(()=>permissions.reduce<Record<string,Permission[]>>((result,item)=>{(result[item.module]??=[]).push(item);return result},{}),[permissions]);
 const toggle=(id:number)=>setSelected(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next});
 const all=(items:Permission[])=>setSelected(current=>{const next=new Set(current),enable=items.some(item=>!next.has(item.id));items.forEach(item=>enable?next.add(item.id):next.delete(item.id));return next});
 const save=async()=>{setError("");try{await visitorsApi.saveRolePermissions(roleId,[...selected]);setMessage("Role permissions updated successfully.")}catch(e){setError(apiErrorMessage(e))}};
 const create=async()=>{try{await api.post("/roles",{name});setName("");setMessage("Role created successfully.");await load()}catch(e){setError(apiErrorMessage(e))}};
 const remove=async()=>{if(!role||!confirm(`Delete role ${role.name}?`))return;try{await api.delete(`/roles/${role.id}`);setMessage("Role deleted.");setRoleId(0);await load()}catch(e){setError(apiErrorMessage(e))}};
 return <div className="space-y-6"><header><p className="eyebrow">Administration</p><h1 className="page-title">Roles & Permission Matrix</h1><p className="page-subtitle">Control detailed module actions while protecting system roles and Admin access.</p></header>{error&&<div className="notice-error">{error}</div>}{message&&<div className="notice-success">{message}</div>}<section className="panel"><div className="flex flex-wrap gap-3"><input className="field-control" value={name} onChange={e=>setName(e.target.value)} placeholder="New role name"/><button className="primary-button" disabled={name.trim().length<2} onClick={create}>Add Role</button><select className="field-control ml-auto" value={roleId} onChange={e=>setRoleId(Number(e.target.value))}>{roles.map(item=><option value={item.id} key={item.id}>{item.name}{item.is_system?" (System)":""}</option>)}</select>{role&&!role.is_system&&<button className="secondary-button text-red-600" onClick={remove}>Delete Role</button>}</div></section>{loading?<div className="panel">Loading permission matrix…</div>:<div className="space-y-4">{Object.entries(groups).map(([module,items])=><section className="panel" key={module}><div className="flex items-center justify-between"><h2 className="text-lg font-bold capitalize">{module.replaceAll("_"," ").replaceAll("."," / ")}</h2><button className="secondary-button" disabled={role?.name==="Admin"} onClick={()=>all(items)}>Select all for module</button></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{items.map(item=><label className="flex items-center gap-3 rounded-lg border border-slate-200 p-3 text-sm" key={item.id}><input type="checkbox" disabled={role?.name==="Admin"} checked={role?.name==="Admin"||selected.has(item.id)} onChange={()=>toggle(item.id)}/><span className="capitalize">{item.action.replaceAll("_"," ")}</span></label>)}</div></section>)}</div>}<div className="sticky bottom-4 flex justify-end"><button className="primary-button shadow-lg" disabled={!roleId||role?.name==="Admin"} onClick={save}>Save Role Permissions</button></div></div>
}
