from enum import Enum
from typing import Any

from fastapi.encoders import jsonable_encoder
from sqlalchemy.orm import Session

from app.models.audit_log import AuditLog


class AuditAction(str, Enum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    VERIFY = "VERIFY"
    LOGIN = "LOGIN"
    SPONSORSHIP_STATUS_CHANGE = "SPONSORSHIP_STATUS_CHANGE"
    BED_ALLOCATION = "BED_ALLOCATION"
    BED_TRANSFER = "BED_TRANSFER"
    BED_VACATION = "BED_VACATION"
    MEDICAL_PROFILE_CREATE = "MEDICAL_PROFILE_CREATE"
    MEDICAL_PROFILE_UPDATE = "MEDICAL_PROFILE_UPDATE"
    MEDICAL_VISIT_CREATE = "MEDICAL_VISIT_CREATE"
    MEDICAL_VISIT_UPDATE = "MEDICAL_VISIT_UPDATE"
    MEDICATION_CREATE = "MEDICATION_CREATE"
    MEDICATION_UPDATE = "MEDICATION_UPDATE"
    VACCINATION_CREATE = "VACCINATION_CREATE"
    VACCINATION_UPDATE = "VACCINATION_UPDATE"
    MEDICAL_DOCUMENT_UPLOAD = "MEDICAL_DOCUMENT_UPLOAD"
    MEDICAL_DOCUMENT_DELETE = "MEDICAL_DOCUMENT_DELETE"
    SCHOOL_CREATE = "SCHOOL_CREATE"
    SCHOOL_UPDATE = "SCHOOL_UPDATE"
    SCHOOL_DELETE = "SCHOOL_DELETE"
    EDUCATION_RECORD_CREATE = "EDUCATION_RECORD_CREATE"
    EDUCATION_RECORD_UPDATE = "EDUCATION_RECORD_UPDATE"
    EXAM_RESULT_CREATE = "EXAM_RESULT_CREATE"
    EXAM_RESULT_UPDATE = "EXAM_RESULT_UPDATE"
    ATTENDANCE_CREATE = "ATTENDANCE_CREATE"
    ATTENDANCE_UPDATE = "ATTENDANCE_UPDATE"
    EDUCATION_DOCUMENT_UPLOAD = "EDUCATION_DOCUMENT_UPLOAD"
    EDUCATION_DOCUMENT_DELETE = "EDUCATION_DOCUMENT_DELETE"
    CASE_PROFILE_CREATE = "CASE_PROFILE_CREATE"
    CASE_PROFILE_UPDATE = "CASE_PROFILE_UPDATE"
    CASE_PROFILE_CLOSE = "CASE_PROFILE_CLOSE"
    CASE_PROFILE_REOPEN = "CASE_PROFILE_REOPEN"
    CASE_NOTE_CREATE = "CASE_NOTE_CREATE"
    CASE_NOTE_UPDATE = "CASE_NOTE_UPDATE"
    CASE_NOTE_DELETE = "CASE_NOTE_DELETE"
    COUNSELING_SESSION_CREATE = "COUNSELING_SESSION_CREATE"
    COUNSELING_SESSION_UPDATE = "COUNSELING_SESSION_UPDATE"
    COUNSELING_SESSION_DELETE = "COUNSELING_SESSION_DELETE"
    INCIDENT_CREATE = "INCIDENT_CREATE"
    INCIDENT_UPDATE = "INCIDENT_UPDATE"
    INCIDENT_REVIEW = "INCIDENT_REVIEW"
    INCIDENT_CLOSE = "INCIDENT_CLOSE"
    INCIDENT_DELETE = "INCIDENT_DELETE"
    CARE_PLAN_CREATE = "CARE_PLAN_CREATE"
    CARE_PLAN_UPDATE = "CARE_PLAN_UPDATE"
    CARE_PLAN_COMPLETE = "CARE_PLAN_COMPLETE"
    CARE_PLAN_CANCEL = "CARE_PLAN_CANCEL"
    CARE_PLAN_DELETE = "CARE_PLAN_DELETE"
    CASE_REVIEW_CREATE = "CASE_REVIEW_CREATE"
    CASE_REVIEW_UPDATE = "CASE_REVIEW_UPDATE"
    CASE_REVIEW_DELETE = "CASE_REVIEW_DELETE"
    EXPORT_EXCEL = "EXPORT_EXCEL"
    EXPORT_PDF = "EXPORT_PDF"
    IMPORT_PREVIEW = "IMPORT_PREVIEW"
    IMPORT_COMMIT = "IMPORT_COMMIT"
    USER_CREATE = "USER_CREATE"
    USER_UPDATE = "USER_UPDATE"
    USER_ACTIVATE = "USER_ACTIVATE"
    USER_DEACTIVATE = "USER_DEACTIVATE"
    USER_ROLE_ASSIGN = "USER_ROLE_ASSIGN"
    USER_PASSWORD_RESET = "USER_PASSWORD_RESET"
    USER_PASSWORD_CHANGE = "USER_PASSWORD_CHANGE"
    USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
    USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
    DAILY_ATTENDANCE_CREATE = "DAILY_ATTENDANCE_CREATE"
    DAILY_ATTENDANCE_UPDATE = "DAILY_ATTENDANCE_UPDATE"
    DAILY_ATTENDANCE_DELETE = "DAILY_ATTENDANCE_DELETE"
    DAILY_ATTENDANCE_BULK_MARK = "DAILY_ATTENDANCE_BULK_MARK"
    ROLE_CREATED="ROLE_CREATED";ROLE_UPDATED="ROLE_UPDATED";ROLE_DELETED="ROLE_DELETED";ROLE_PERMISSIONS_UPDATED="ROLE_PERMISSIONS_UPDATED";USER_ROLES_UPDATED="USER_ROLES_UPDATED"
    VISITOR_CREATED="VISITOR_CREATED";VISITOR_UPDATED="VISITOR_UPDATED";VISITOR_VERIFIED="VISITOR_VERIFIED";VISITOR_BLOCKED="VISITOR_BLOCKED";VISITOR_ACTIVATED="VISITOR_ACTIVATED";VISITOR_DEACTIVATED="VISITOR_DEACTIVATED"
    CHILD_VISIT_CREATED="CHILD_VISIT_CREATED";CHILD_VISIT_UPDATED="CHILD_VISIT_UPDATED";CHILD_VISIT_APPROVED="CHILD_VISIT_APPROVED";CHILD_VISIT_REJECTED="CHILD_VISIT_REJECTED";CHILD_VISIT_CHECKED_IN="CHILD_VISIT_CHECKED_IN";CHILD_VISIT_CHECKED_OUT="CHILD_VISIT_CHECKED_OUT";CHILD_VISIT_CANCELLED="CHILD_VISIT_CANCELLED"
    ORGANIZATION_PROFILE_UPDATED = "ORGANIZATION_PROFILE_UPDATED"
    ORGANIZATION_LOGO_UPLOADED = "ORGANIZATION_LOGO_UPLOADED"
    ORGANIZATION_LOGO_DELETED = "ORGANIZATION_LOGO_DELETED"
    DEVELOPMENT_INDICATOR_CREATED = "DEVELOPMENT_INDICATOR_CREATED"
    DEVELOPMENT_INDICATOR_UPDATED = "DEVELOPMENT_INDICATOR_UPDATED"
    DEVELOPMENT_INDICATOR_ACTIVATED = "DEVELOPMENT_INDICATOR_ACTIVATED"
    DEVELOPMENT_INDICATOR_DEACTIVATED = "DEVELOPMENT_INDICATOR_DEACTIVATED"
    CHILD_DEVELOPMENT_OBSERVATION_CREATED = "CHILD_DEVELOPMENT_OBSERVATION_CREATED"
    CHILD_DEVELOPMENT_OBSERVATION_UPDATED = "CHILD_DEVELOPMENT_OBSERVATION_UPDATED"
    CHILD_DEVELOPMENT_OBSERVATION_SUBMITTED = "CHILD_DEVELOPMENT_OBSERVATION_SUBMITTED"
    CHILD_DEVELOPMENT_OBSERVATION_REVIEWED = "CHILD_DEVELOPMENT_OBSERVATION_REVIEWED"
    CHILD_DEVELOPMENT_OBSERVATION_CLOSED = "CHILD_DEVELOPMENT_OBSERVATION_CLOSED"
    CHILD_DEVELOPMENT_OBSERVATION_ARCHIVED = "CHILD_DEVELOPMENT_OBSERVATION_ARCHIVED"
    CHILD_DEVELOPMENT_AI_SUMMARY_GENERATED = "CHILD_DEVELOPMENT_AI_SUMMARY_GENERATED"
    CHILD_DEVELOPMENT_AI_SUMMARY_UPDATED = "CHILD_DEVELOPMENT_AI_SUMMARY_UPDATED"
    CHILD_DEVELOPMENT_AI_SUMMARY_REVIEWED = "CHILD_DEVELOPMENT_AI_SUMMARY_REVIEWED"
    CHILD_DEVELOPMENT_AI_SUMMARY_APPROVED = "CHILD_DEVELOPMENT_AI_SUMMARY_APPROVED"
    CHILD_DEVELOPMENT_AI_SUMMARY_REJECTED = "CHILD_DEVELOPMENT_AI_SUMMARY_REJECTED"
    CHILD_DEVELOPMENT_AI_SUMMARY_ARCHIVED = "CHILD_DEVELOPMENT_AI_SUMMARY_ARCHIVED"
    BEHAVIOR_SUPPORT_PLAN_CREATED = "BEHAVIOR_SUPPORT_PLAN_CREATED"
    BEHAVIOR_SUPPORT_PLAN_GENERATED = "BEHAVIOR_SUPPORT_PLAN_GENERATED"
    BEHAVIOR_SUPPORT_PLAN_UPDATED = "BEHAVIOR_SUPPORT_PLAN_UPDATED"
    BEHAVIOR_SUPPORT_PLAN_STATUS_CHANGED = "BEHAVIOR_SUPPORT_PLAN_STATUS_CHANGED"
    BEHAVIOR_SUPPORT_PLAN_NOTE_CREATED = "BEHAVIOR_SUPPORT_PLAN_NOTE_CREATED"
    BEHAVIOR_SUPPORT_PLAN_NOTE_UPDATED = "BEHAVIOR_SUPPORT_PLAN_NOTE_UPDATED"
    BEHAVIOR_SUPPORT_PLAN_NOTE_DELETED = "BEHAVIOR_SUPPORT_PLAN_NOTE_DELETED"


class AuditModule(str, Enum):
    AUTH = "AUTH"
    CHILDREN = "CHILDREN"
    DOCUMENTS = "DOCUMENTS"
    USERS = "USERS"
    ROLES = "ROLES"
    SPONSORS = "SPONSORS"
    SPONSORSHIPS = "SPONSORSHIPS"
    ACCOMMODATION = "ACCOMMODATION"
    BED_ALLOCATIONS = "BED_ALLOCATIONS"
    MEDICAL = "MEDICAL"
    EDUCATION = "EDUCATION"
    CASE_MANAGEMENT = "CASE_MANAGEMENT"
    CASE_PROFILE = "CASE_PROFILE"
    CASE_NOTE = "CASE_NOTE"
    COUNSELING = "COUNSELING"
    INCIDENT = "INCIDENT"
    CARE_PLAN = "CARE_PLAN"
    CASE_REVIEW = "CASE_REVIEW"
    IMPORT_EXPORT = "IMPORT_EXPORT"
    USER_ADMINISTRATION = "USER_ADMINISTRATION"
    DAILY_ATTENDANCE = "DAILY_ATTENDANCE"
    VISITORS="VISITORS";CHILD_VISITS="CHILD_VISITS"
    ORGANIZATION_PROFILE = "ORGANIZATION_PROFILE"
    CHILD_DEVELOPMENT = "CHILD_DEVELOPMENT"


def add_audit_log(
    db: Session,
    *,
    user_id: int | None,
    action: AuditAction,
    module: AuditModule,
    record_id: int | None = None,
    old_values: dict[str, Any] | None = None,
    new_values: dict[str, Any] | None = None,
) -> AuditLog:
    log = AuditLog(
        user_id=user_id,
        action=action.value,
        module=module.value,
        record_id=record_id,
        old_values=jsonable_encoder(old_values) if old_values is not None else None,
        new_values=jsonable_encoder(new_values) if new_values is not None else None,
    )
    db.add(log)
    return log
