from datetime import datetime, timezone
from io import BytesIO
from pathlib import Path
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


SENSITIVE_WORDS = (
    "password",
    "token",
    "hash",
    "cnic",
    "passport",
    "mobile",
    "address",
    "diagnosis",
    "treatment",
    "confidential",
    "restricted",
)


def _branding(branding: dict | None) -> dict:
    base = {
        "organization_name": "Child Care Management System",
        "short_name": "CCMS",
        "logo_path": None,
        "address": "Not configured",
        "city": None,
        "district": None,
        "province": None,
        "country": None,
        "phone": None,
        "email": None,
        "report_footer_text": "This report is system generated.",
        "primary_color": "#174A7E",
        "secondary_color": "#EAF2F9",
        "authorized_signatory_name": None,
        "authorized_signatory_designation": None,
    }
    for key, value in (branding or {}).items():
        if value not in (None, ""):
            base[key] = value
    return base


def _color(value: str | None, fallback: str) -> colors.HexColor:
    try:
        return colors.HexColor(value or fallback)
    except Exception:
        return colors.HexColor(fallback)


def _contact_line(brand: dict) -> str:
    parts = [brand.get("address"), brand.get("city"), brand.get("district"), brand.get("province"), brand.get("country")]
    location = ", ".join(str(item) for item in parts if item)
    contact = " | ".join(str(item) for item in [brand.get("phone"), brand.get("email")] if item)
    return " | ".join(item for item in [location, contact] if item) or "Not configured"


def _logo_cell(brand: dict, width: int = 58, height: int = 46):
    path = brand.get("logo_path")
    if path and Path(path).is_file():
        try:
            return Image(path, width=width, height=height)
        except Exception:
            pass
    return Paragraph(
        f"<b>{escape(str(brand.get('short_name') or 'CCMS'))}</b>",
        ParagraphStyle("LogoFallback", fontName="Helvetica-Bold", fontSize=16, alignment=TA_CENTER, textColor=colors.white),
    )


def _report_header(title: str, username: str, filters: dict | None, page_width: float, styles, brand: dict):
    generated = datetime.now(timezone.utc)
    primary = _color(brand.get("primary_color"), "#174A7E")
    secondary = _color(brand.get("secondary_color"), "#EAF2F9")
    white_text = ParagraphStyle("HeaderWhite", parent=styles["Normal"], fontSize=8.5, leading=11, textColor=colors.white)
    title_style = ParagraphStyle("HeaderTitle", parent=styles["Normal"], fontName="Helvetica-Bold", fontSize=12, leading=15, textColor=colors.white, alignment=TA_LEFT)
    org = Paragraph(
        f"<b>{escape(str(brand['organization_name']))}</b><br/><font size='8'>{escape(_contact_line(brand))}</font>",
        title_style,
    )
    report = Paragraph(
        f"<b>{escape(title)}</b><br/><font size='8'>Generated by {escape(username)}<br/>Generated at {generated.strftime('%d %B %Y, %H:%M UTC')}</font>",
        white_text,
    )
    header = Table([[_logo_cell(brand), org, report]], colWidths=[70, page_width * 0.52, page_width - page_width * 0.52 - 118])
    header.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), primary),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 9),
    ]))
    filter_text = ", ".join(f"{key.replace('_', ' ').title()}: {value}" for key, value in (filters or {}).items() if value not in (None, "", [], {})) or "All available records"
    meta = ParagraphStyle("ReportMeta", parent=styles["Normal"], fontSize=8, leading=11, textColor=colors.HexColor("#50677D"))
    filter_box = Table([[Paragraph(f"<b>Filters:</b> {escape(filter_text)}", meta)]], colWidths=[page_width - 48])
    filter_box.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), secondary),
        ("BOX", (0, 0), (-1, -1), .4, colors.HexColor("#B8CADB")),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return [header, Spacer(1, 7), filter_box, Spacer(1, 8)]


def _footer(brand: dict, page_width: float, margin: int):
    footer_text = brand.get("report_footer_text") or "This report is system generated."

    def draw(canvas, _doc):
        canvas.saveState()
        canvas.setStrokeColor(colors.HexColor("#C9D6E2"))
        canvas.line(margin, 28, page_width - margin, 28)
        canvas.setFont("Helvetica", 7.3)
        canvas.setFillColor(colors.HexColor("#60758A"))
        canvas.drawString(margin, 16, escape(str(footer_text))[:120])
        canvas.drawCentredString(page_width / 2, 16, "This report is system generated by CCMS.")
        canvas.drawRightString(page_width - margin, 16, f"Page {canvas.getPageNumber()}")
        canvas.restoreState()

    return draw


def build_pdf_report(title, rows, username, filters, branding: dict | None = None):
    brand = _branding(branding)
    columns = [key for key in (list(rows[0]) if rows else []) if not any(word in key.lower() for word in SENSITIVE_WORDS)]
    page_size = landscape(A4) if len(columns) > 7 else A4
    page_width, _ = page_size
    out = BytesIO()
    doc = SimpleDocTemplate(out, pagesize=page_size, rightMargin=24, leftMargin=24, topMargin=24, bottomMargin=34, title=f"{title} Report", author=brand["short_name"])
    styles = getSampleStyleSheet()
    cell = ParagraphStyle("ReportCell", parent=styles["Normal"], fontSize=6.5, leading=8)
    head = ParagraphStyle("ReportHead", parent=cell, fontName="Helvetica-Bold", textColor=colors.white)
    meta = ParagraphStyle("ReportMeta2", parent=styles["Normal"], fontSize=8, textColor=colors.HexColor("#50677D"))
    story = _report_header(f"{title} Report", username, filters, page_width, styles, brand)
    status_values = [str(value).lower() for row in rows for key, value in row.items() if "status" in key.lower() and value is not None]
    summary = [("Total Records", len(rows)), ("Active", status_values.count("active")), ("Inactive", status_values.count("inactive")), ("Pending", sum(1 for value in status_values if "pending" in value)), ("Critical", status_values.count("critical"))]
    summary = [item for item in summary if item[0] == "Total Records" or item[1]]
    if summary:
        cards = Table([[Paragraph(f"<b>{escape(name)}</b><br/><font size='13'>{count}</font>", ParagraphStyle(f"Card{name}", parent=meta, alignment=TA_CENTER)) for name, count in summary]], colWidths=[(page_width - 48) / len(summary)] * len(summary))
        cards.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, -1), _color(brand.get("secondary_color"), "#EAF2F9")), ("BOX", (0, 0), (-1, -1), .5, colors.HexColor("#B8CADB")), ("INNERGRID", (0, 0), (-1, -1), .5, colors.HexColor("#B8CADB")), ("TOPPADDING", (0, 0), (-1, -1), 7), ("BOTTOMPADDING", (0, 0), (-1, -1), 7)]))
        story.extend([cards, Spacer(1, 10)])
    if rows and columns:
        data = [[Paragraph("S. No.", head)] + [Paragraph(escape(column.replace("_", " ").title()), head) for column in columns]]
        for number, row in enumerate(rows, 1):
            data.append([Paragraph(str(number), cell)] + [Paragraph(escape(str(row.get(column) if row.get(column) not in (None, "") else "-"))[:500], cell) for column in columns])
        widths = [30] + [(page_width - 78) / len(columns)] * len(columns)
        table = Table(data, repeatRows=1, colWidths=widths)
        table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), _color(brand.get("primary_color"), "#315F88")), ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F4F7FA")]), ("GRID", (0, 0), (-1, -1), .3, colors.HexColor("#B9C8D5")), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 4), ("RIGHTPADDING", (0, 0), (-1, -1), 4), ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4)]))
        story.append(table)
    else:
        story.append(Paragraph("No records were found for the selected report and filters.", ParagraphStyle("ReportEmpty", parent=meta, fontName="Helvetica-Oblique", spaceBefore=12)))
    doc.build(story, onFirstPage=_footer(brand, page_width, 24), onLaterPages=_footer(brand, page_width, 24))
    out.seek(0)
    return out


def build_full_profile_pdf(profile: dict, username: str, branding: dict | None = None):
    brand = _branding(branding)
    out = BytesIO()
    page_width, _ = A4
    doc = SimpleDocTemplate(out, pagesize=A4, rightMargin=36, leftMargin=36, topMargin=34, bottomMargin=42, title="Full Child Profile Report", author=brand["short_name"])
    styles = getSampleStyleSheet()
    normal = ParagraphStyle("ProfileNormal", parent=styles["Normal"], fontName="Helvetica", fontSize=8.5, leading=12, textColor=colors.HexColor("#243447"))
    label = ParagraphStyle("ProfileLabel", parent=normal, fontName="Helvetica-Bold", fontSize=7.5, textColor=colors.HexColor("#52677D"))
    small = ParagraphStyle("ProfileSmall", parent=normal, fontSize=7.5, leading=10)
    empty_style = ParagraphStyle("Empty", parent=normal, textColor=colors.HexColor("#6B7C8F"), fontName="Helvetica-Oblique", leftIndent=8)

    def para(value, style=normal):
        if value is None or value == "":
            value = "-"
        return Paragraph(escape(str(value)), style)

    story = _report_header("Full Child Profile Report", username, {}, page_width, styles, brand)
    identity = list(profile["identity"].items())
    identity_rows = []
    for index in range(0, len(identity), 2):
        row = []
        for key, value in identity[index:index + 2]:
            row.extend([para(key, label), para(value)])
        while len(row) < 4:
            row.extend([Paragraph("", label), Paragraph("", normal)])
        identity_rows.append(row)
    identity_table = Table(identity_rows, colWidths=[72, 152, 72, 152])
    identity_commands = [("GRID", (0, 0), (-1, -1), .35, colors.HexColor("#C9D6E2")), ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F2F6FA")), ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#F2F6FA")), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 7), ("RIGHTPADDING", (0, 0), (-1, -1), 7), ("TOPPADDING", (0, 0), (-1, -1), 6), ("BOTTOMPADDING", (0, 0), (-1, -1), 6)]
    identity_table.setStyle(TableStyle(identity_commands))
    photo_path = profile.get("child_photo_path")
    photo = Paragraph("<b>No Photo Available</b>", ParagraphStyle("NoPhoto", parent=small, alignment=TA_CENTER, textColor=colors.HexColor("#60758A")))
    if photo_path and Path(photo_path).is_file():
        try:
            photo = Image(photo_path, width=64, height=76)
        except Exception:
            pass
    identity_block = Table([[photo, identity_table]], colWidths=[75, 448])
    identity_block.setStyle(TableStyle([("BOX", (0, 0), (0, 0), .5, colors.HexColor("#C9D6E2")), ("VALIGN", (0, 0), (-1, -1), "MIDDLE"), ("ALIGN", (0, 0), (0, 0), "CENTER"), ("LEFTPADDING", (0, 0), (0, 0), 5), ("RIGHTPADDING", (0, 0), (0, 0), 5)]))
    story.extend([identity_block, Spacer(1, 12)])
    for section in profile["sections"]:
        section_title = Table([[para(section["title"], ParagraphStyle("Section", parent=normal, fontName="Helvetica-Bold", fontSize=10, textColor=_color(brand.get("primary_color"), "#174A7E")))]], colWidths=[523])
        section_title.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, -1), _color(brand.get("secondary_color"), "#EAF2F9")), ("BOX", (0, 0), (-1, -1), .6, colors.HexColor("#AFC4D7")), ("LEFTPADDING", (0, 0), (-1, -1), 9), ("TOPPADDING", (0, 0), (-1, -1), 6), ("BOTTOMPADDING", (0, 0), (-1, -1), 6)]))
        story.extend([section_title, Spacer(1, 5)])
        fields = section.get("fields", [])
        if fields:
            field_rows = []
            for index in range(0, len(fields), 2):
                row = []
                for key, value in fields[index:index + 2]:
                    row.extend([para(key, label), para(value)])
                while len(row) < 4:
                    row.extend([Paragraph("", label), Paragraph("", normal)])
                field_rows.append(row)
            table = Table(field_rows, colWidths=[105, 156.5, 105, 156.5])
            table.setStyle(TableStyle([("BOX", (0, 0), (-1, -1), .4, colors.HexColor("#D3DEE8")), ("INNERGRID", (0, 0), (-1, -1), .3, colors.HexColor("#E2E9EF")), ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F8FAFC")), ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#F8FAFC")), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 7), ("RIGHTPADDING", (0, 0), (-1, -1), 7), ("TOPPADDING", (0, 0), (-1, -1), 5), ("BOTTOMPADDING", (0, 0), (-1, -1), 5)]))
            story.append(table)
        if section.get("note"):
            story.extend([Spacer(1, 4), para(section["note"], empty_style)])
        rows = section.get("rows", [])
        columns = section.get("columns", [])
        if rows:
            story.append(Spacer(1, 6))
            data = [[para(column, ParagraphStyle("TableHead", parent=small, fontName="Helvetica-Bold", textColor=colors.white)) for column in columns]] + [[para(value, small) for value in row] for row in rows]
            detail = Table(data, colWidths=[523 / len(columns)] * len(columns), repeatRows=1)
            detail.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), _color(brand.get("primary_color"), "#4D7398")), ("GRID", (0, 0), (-1, -1), .3, colors.HexColor("#CBD6E0")), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 5), ("RIGHTPADDING", (0, 0), (-1, -1), 5), ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4)]))
            story.append(detail)
        elif section.get("empty"):
            story.extend([Spacer(1, 5), para(section["empty"], empty_style)])
        story.append(Spacer(1, 10))
    doc.build(story, onFirstPage=_footer(brand, page_width, 36), onLaterPages=_footer(brand, page_width, 36))
    out.seek(0)
    return out


def build_attendance_pdf(title: str, rows: list[dict], username: str, period: str, columns: list[tuple[str, str]], branding: dict | None = None):
    brand = _branding(branding)
    out = BytesIO()
    width, _ = landscape(A4)
    doc = SimpleDocTemplate(out, pagesize=landscape(A4), rightMargin=24, leftMargin=24, topMargin=24, bottomMargin=34, title=title, author=brand["short_name"])
    styles = getSampleStyleSheet()
    small = ParagraphStyle("AttendanceCell", parent=styles["Normal"], fontSize=6.5, leading=8)
    head = ParagraphStyle("AttendanceHead", parent=small, fontName="Helvetica-Bold", textColor=colors.white)
    story = _report_header(title, username, {"period": period}, width, styles, brand)
    data = [[Paragraph("S. No.", head)] + [Paragraph(escape(label), head) for _, label in columns]]
    for number, row in enumerate(rows, 1):
        data.append([Paragraph(str(number), small)] + [Paragraph(escape(str(row.get(key) if row.get(key) not in (None, "") else "-")), small) for key, _ in columns])
    if len(data) == 1:
        data.append([Paragraph("-", small), Paragraph("No attendance records found for the selected period.", small)] + [Paragraph("", small) for _ in columns[1:]])
    table = Table(data, repeatRows=1, colWidths=[28] + [(width - 76) / len(columns)] * len(columns))
    table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), _color(brand.get("primary_color"), "#174A7E")), ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F4F7FA")]), ("GRID", (0, 0), (-1, -1), .3, colors.HexColor("#B8C7D4")), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 4), ("RIGHTPADDING", (0, 0), (-1, -1), 4), ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4)]))
    story.append(table)
    doc.build(story, onFirstPage=_footer(brand, width, 24), onLaterPages=_footer(brand, width, 24))
    out.seek(0)
    return out
