from datetime import datetime, timezone
from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import Image, KeepTogether, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from pathlib import Path
from xml.sax.saxutils import escape

def build_pdf_report(title, rows, username, filters):
    out=BytesIO(); doc=SimpleDocTemplate(out,pagesize=landscape(A4),rightMargin=24,leftMargin=24,topMargin=24,bottomMargin=28); styles=getSampleStyleSheet()
    story=[Paragraph("CCMS (Child Care Management System)",styles["Title"]),Paragraph(title,styles["Heading2"]),Paragraph(f"Generated {datetime.now(timezone.utc).isoformat()} by {username}",styles["Normal"]),Paragraph(f"Filters: {filters}",styles["Normal"]),Spacer(1,10)]
    columns=list(rows[0]) if rows else ["Result"]; data=[columns]+[[str(r.get(c,""))[:80] for c in columns] for r in rows] if rows else [["No data"]]
    table=Table(data,repeatRows=1); table.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),colors.HexColor("#1F4E78")),("TEXTCOLOR",(0,0),(-1,0),colors.white),("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("FONTSIZE",(0,0),(-1,-1),6),("GRID",(0,0),(-1,-1),.25,colors.grey),("VALIGN",(0,0),(-1,-1),"TOP")]))
    story.append(table)
    def footer(canvas, _): canvas.drawRightString(landscape(A4)[0]-24,15,f"Page {canvas.getPageNumber()}")
    doc.build(story,onFirstPage=footer,onLaterPages=footer); out.seek(0); return out

def build_full_profile_pdf(profile:dict,username:str):
    out=BytesIO();generated=datetime.now(timezone.utc);page_width,page_height=A4
    doc=SimpleDocTemplate(out,pagesize=A4,rightMargin=36,leftMargin=36,topMargin=34,bottomMargin=42,title="Full Child Profile Report",author="CCMS")
    styles=getSampleStyleSheet();normal=ParagraphStyle("ProfileNormal",parent=styles["Normal"],fontName="Helvetica",fontSize=8.5,leading=12,textColor=colors.HexColor("#243447"));label=ParagraphStyle("ProfileLabel",parent=normal,fontName="Helvetica-Bold",fontSize=7.5,textColor=colors.HexColor("#52677D"));small=ParagraphStyle("ProfileSmall",parent=normal,fontSize=7.5,leading=10);empty_style=ParagraphStyle("Empty",parent=normal,textColor=colors.HexColor("#6B7C8F"),fontName="Helvetica-Oblique",leftIndent=8)
    def para(value,style=normal):
        if value is None or value=="":value="Not recorded"
        return Paragraph(escape(str(value)),style)
    header=Table([[Paragraph("<b>CCMS</b>",ParagraphStyle("Brand",parent=normal,fontSize=18,leading=20,textColor=colors.white)),Paragraph("<b>Child Care Management System</b><br/><font size='9'>Full Child Profile Report</font>",ParagraphStyle("HeadText",parent=normal,fontSize=11,leading=15,textColor=colors.white,alignment=TA_LEFT))]],colWidths=[95,428])
    header.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),colors.HexColor("#174A7E")),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("LEFTPADDING",(0,0),(-1,-1),14),("RIGHTPADDING",(0,0),(-1,-1),14),("TOPPADDING",(0,0),(-1,-1),12),("BOTTOMPADDING",(0,0),(-1,-1),12)]))
    meta=Table([[para(f"Generated by: {username}",small),para(f"Generated at: {generated.strftime('%d %B %Y, %H:%M UTC')}",small)]],colWidths=[261.5,261.5]);meta.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),colors.HexColor("#EAF2F9")),("BOX",(0,0),(-1,-1),.5,colors.HexColor("#B8CADB")),("LEFTPADDING",(0,0),(-1,-1),8),("RIGHTPADDING",(0,0),(-1,-1),8),("TOPPADDING",(0,0),(-1,-1),6),("BOTTOMPADDING",(0,0),(-1,-1),6)]))
    story=[header,meta,Spacer(1,12)]
    identity=list(profile["identity"].items());identity_rows=[]
    for index in range(0,len(identity),2):
        row=[]
        for key,value in identity[index:index+2]:row.extend([para(key,label),para(value)])
        while len(row)<4:row.extend([Paragraph("",label),Paragraph("",normal)])
        identity_rows.append(row)
    identity_table=Table(identity_rows,colWidths=[72,152,72,152]);identity_commands=[("GRID",(0,0),(-1,-1),.35,colors.HexColor("#C9D6E2")),("BACKGROUND",(0,0),(0,-1),colors.HexColor("#F2F6FA")),("BACKGROUND",(2,0),(2,-1),colors.HexColor("#F2F6FA")),("VALIGN",(0,0),(-1,-1),"TOP"),("LEFTPADDING",(0,0),(-1,-1),7),("RIGHTPADDING",(0,0),(-1,-1),7),("TOPPADDING",(0,0),(-1,-1),6),("BOTTOMPADDING",(0,0),(-1,-1),6)]
    status=str(profile["identity"].get("Status","")).lower();status_color={"active":"#DDF4E7","inactive":"#EDF0F3","draft":"#FFF1C7","discharged":"#E1ECFA","transferred":"#E1ECFA"}.get(status,"#EDF0F3")
    for row_index,row_items in enumerate([identity[i:i+2] for i in range(0,len(identity),2)]):
        for pair_index,(key,_value) in enumerate(row_items):
            if key=="Status":identity_commands.extend([("BACKGROUND",(pair_index*2+1,row_index),(pair_index*2+1,row_index),colors.HexColor(status_color)),("FONTNAME",(pair_index*2+1,row_index),(pair_index*2+1,row_index),"Helvetica-Bold")])
    identity_table.setStyle(TableStyle(identity_commands));photo_path=profile.get("child_photo_path");photo=Paragraph("<b>No Photo</b>",ParagraphStyle("NoPhoto",parent=small,alignment=TA_CENTER,textColor=colors.HexColor("#60758A")))
    if photo_path and Path(photo_path).is_file():
        try:photo=Image(photo_path,width=64,height=76)
        except Exception:pass
    identity_block=Table([[photo,identity_table]],colWidths=[75,448]);identity_block.setStyle(TableStyle([("BOX",(0,0),(0,0),.5,colors.HexColor("#C9D6E2")),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("ALIGN",(0,0),(0,0),"CENTER"),("LEFTPADDING",(0,0),(0,0),5),("RIGHTPADDING",(0,0),(0,0),5)]));story.extend([identity_block,Spacer(1,12)])
    for section in profile["sections"]:
        title=Table([[para(section["title"],ParagraphStyle("Section",parent=normal,fontName="Helvetica-Bold",fontSize=10,textColor=colors.HexColor("#174A7E")))]],colWidths=[523]);title.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),colors.HexColor("#EAF2F9")),("BOX",(0,0),(-1,-1),.6,colors.HexColor("#AFC4D7")),("LEFTPADDING",(0,0),(-1,-1),9),("TOPPADDING",(0,0),(-1,-1),6),("BOTTOMPADDING",(0,0),(-1,-1),6)]));story.extend([title,Spacer(1,5)])
        fields=section.get("fields",[])
        if fields:
            field_rows=[]
            for index in range(0,len(fields),2):
                row=[]
                for key,value in fields[index:index+2]:row.extend([para(key,label),para(value)])
                while len(row)<4:row.extend([Paragraph("",label),Paragraph("",normal)])
                field_rows.append(row)
            table=Table(field_rows,colWidths=[105,156.5,105,156.5]);table.setStyle(TableStyle([("BOX",(0,0),(-1,-1),.4,colors.HexColor("#D3DEE8")),("INNERGRID",(0,0),(-1,-1),.3,colors.HexColor("#E2E9EF")),("BACKGROUND",(0,0),(0,-1),colors.HexColor("#F8FAFC")),("BACKGROUND",(2,0),(2,-1),colors.HexColor("#F8FAFC")),("VALIGN",(0,0),(-1,-1),"TOP"),("LEFTPADDING",(0,0),(-1,-1),7),("RIGHTPADDING",(0,0),(-1,-1),7),("TOPPADDING",(0,0),(-1,-1),5),("BOTTOMPADDING",(0,0),(-1,-1),5)]));story.append(table)
        if section.get("note"):story.extend([Spacer(1,4),para(section["note"],empty_style)])
        rows=section.get("rows",[]);columns=section.get("columns",[])
        if rows:
            story.append(Spacer(1,6));data=[[para(column,ParagraphStyle("TableHead",parent=small,fontName="Helvetica-Bold",textColor=colors.white)) for column in columns]]+[[para(value,small) for value in row] for row in rows]
            widths=[523/len(columns)]*len(columns);detail=Table(data,colWidths=widths,repeatRows=1);detail.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),colors.HexColor("#4D7398")),("GRID",(0,0),(-1,-1),.3,colors.HexColor("#CBD6E0")),("VALIGN",(0,0),(-1,-1),"TOP"),("LEFTPADDING",(0,0),(-1,-1),5),("RIGHTPADDING",(0,0),(-1,-1),5),("TOPPADDING",(0,0),(-1,-1),4),("BOTTOMPADDING",(0,0),(-1,-1),4)]));story.append(detail)
        elif section.get("empty"):story.extend([Spacer(1,5),para(section["empty"],empty_style)])
        story.append(Spacer(1,10))
    def footer(canvas,_doc):
        canvas.saveState();canvas.setStrokeColor(colors.HexColor("#C9D6E2"));canvas.line(36,29,page_width-36,29);canvas.setFont("Helvetica",7.5);canvas.setFillColor(colors.HexColor("#60758A"));canvas.drawString(36,17,"This report is system generated by CCMS.");canvas.drawRightString(page_width-36,17,f"Page {canvas.getPageNumber()}");canvas.restoreState()
    doc.build(story,onFirstPage=footer,onLaterPages=footer);out.seek(0);return out

def build_attendance_pdf(title:str,rows:list[dict],username:str,period:str,columns:list[tuple[str,str]]):
    out=BytesIO();generated=datetime.now(timezone.utc);width,_=landscape(A4)
    doc=SimpleDocTemplate(out,pagesize=landscape(A4),rightMargin=24,leftMargin=24,topMargin=24,bottomMargin=34,title=title,author="CCMS")
    styles=getSampleStyleSheet();small=ParagraphStyle("AttendanceCell",parent=styles["Normal"],fontSize=6.5,leading=8);head=ParagraphStyle("AttendanceHead",parent=small,fontName="Helvetica-Bold",textColor=colors.white)
    story=[Paragraph("CCMS - Child Care Management System",styles["Title"]),Paragraph(title,styles["Heading2"]),Paragraph(f"Period: {escape(period)} | Generated by: {escape(username)} | Generated at: {generated.strftime('%d %B %Y, %H:%M UTC')}",styles["Normal"]),Spacer(1,10)]
    data=[[Paragraph("S. No.",head)]+[Paragraph(escape(label),head) for _,label in columns]]
    for number,row in enumerate(rows,1):data.append([Paragraph(str(number),small)]+[Paragraph(escape(str(row.get(key) if row.get(key) not in (None,"") else "-")),small) for key,_ in columns])
    if len(data)==1:data.append([Paragraph("-",small),Paragraph("No attendance records found for the selected period.",small)]+[Paragraph("",small) for _ in columns[1:]])
    table=Table(data,repeatRows=1,colWidths=[28]+[(width-76)/len(columns)]*len(columns));table.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),colors.HexColor("#174A7E")),("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white,colors.HexColor("#F4F7FA")]),("GRID",(0,0),(-1,-1),.3,colors.HexColor("#B8C7D4")),("VALIGN",(0,0),(-1,-1),"TOP"),("LEFTPADDING",(0,0),(-1,-1),4),("RIGHTPADDING",(0,0),(-1,-1),4),("TOPPADDING",(0,0),(-1,-1),4),("BOTTOMPADDING",(0,0),(-1,-1),4)]));story.append(table)
    def footer(canvas,_doc):
        canvas.saveState();canvas.setFont("Helvetica",7);canvas.setFillColor(colors.HexColor("#60758A"));canvas.drawString(24,16,"This report is system generated by CCMS.");canvas.drawRightString(width-24,16,f"Page {canvas.getPageNumber()}");canvas.restoreState()
    doc.build(story,onFirstPage=footer,onLaterPages=footer);out.seek(0);return out
