"use client";
import { useEffect,useMemo,useState } from "react";
import { api,apiErrorMessage } from "@/lib/api";

export type Mutation={label:string;path:string;schema?:string;method?:"post"|"put"|"delete";confirm?:string;adminOnly?:boolean;managerOnly?:boolean};
type JsonSchema={type?:string;format?:string;title?:string;default?:unknown;enum?:unknown[];$ref?:string;anyOf?:JsonSchema[];items?:JsonSchema;properties?:Record<string,JsonSchema>;required?:string[];allOf?:JsonSchema[]};
type OpenApi={components?:{schemas?:Record<string,JsonSchema>}};
const relationEndpoints:Record<string,{path:string;value:string;text:string[]}>= {child_id:{path:"/children",value:"id",text:["child_id","full_name"]},sponsor_id:{path:"/sponsors",value:"id",text:["sponsor_code","full_name"]},building_id:{path:"/buildings",value:"id",text:["building_code","building_name"]},block_id:{path:"/blocks",value:"id",text:["block_code","block_name"]},floor_id:{path:"/floors",value:"id",text:["floor_no","floor_name"]},room_id:{path:"/rooms",value:"id",text:["room_code","room_name"]},bed_id:{path:"/reports/vacant-beds",value:"id",text:["bed_code","bed_name"]},school_id:{path:"/schools",value:"id",text:["school_code","school_name"]},education_record_id:{path:"/reports/students",value:"id",text:["class_level","academic_year"]},role_ids:{path:"/roles",value:"id",text:["name"]}};
const human=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
function resolve(schema:JsonSchema|undefined,schemas:Record<string,JsonSchema>):JsonSchema{if(!schema)return {};if(schema.$ref)return resolve(schemas[schema.$ref.split("/").pop()||""],schemas);if(schema.allOf){return schema.allOf.map(item=>resolve(item,schemas)).reduce((result,item)=>({...result,...item,properties:{...result.properties,...item.properties},required:[...(result.required||[]),...(item.required||[])]}),{} as JsonSchema)}const concrete=schema.anyOf?.find(item=>item.type!=="null")||schema;return concrete.$ref?resolve(concrete,schemas):concrete}
function pathFields(path:string){return [...path.matchAll(/\{([^}]+)\}/g)].map(match=>match[1]).filter(name=>name!=="id")}
function buildPayload(schema:JsonSchema,schemas:Record<string,JsonSchema>,values:Record<string,string>){const payload:Record<string,unknown>={};for(const [name,raw] of Object.entries(schema.properties||{})){const definition=resolve(raw,schemas);const value=values[name];if(value===""&&!schema.required?.includes(name))continue;if(definition.type==="integer"||definition.type==="number")payload[name]=Number(value);else if(definition.type==="boolean")payload[name]=value==="true";else if(definition.type==="array")payload[name]=value.split(",").map(item=>Number.isNaN(Number(item.trim()))?item.trim():Number(item.trim())).filter(Boolean);else payload[name]=value}return payload}
export function DynamicRecordModal({mutation,initial,onClose,onSaved}:{mutation:Mutation;initial?:Record<string,unknown>;onClose:()=>void;onSaved:(message:string)=>void}){
 const [openApi,setOpenApi]=useState<OpenApi>({});const [values,setValues]=useState<Record<string,string>>({});const [options,setOptions]=useState<Record<string,Record<string,unknown>[]>>({});const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const schemas=openApi.components?.schemas||{};const schema=resolve(mutation.schema?schemas[mutation.schema]:undefined,schemas);const properties=useMemo(()=>({...Object.fromEntries(pathFields(mutation.path).map(name=>[name,{type:"integer",title:human(name)}])),...(schema.properties||{})}),[mutation.path,schema.properties]);
 useEffect(()=>{api.get<OpenApi>("/openapi.json").then(response=>{setOpenApi(response.data);const target=resolve(mutation.schema?response.data.components?.schemas?.[mutation.schema]:undefined,response.data.components?.schemas||{});const fields:Record<string,JsonSchema>={...Object.fromEntries(pathFields(mutation.path).map(name=>[name,{type:"integer"} as JsonSchema])),...(target.properties||{})};setValues(Object.fromEntries(Object.entries(fields).map(([name,definition])=>[name,String(initial?.[name]??definition.default??"")])));return Promise.all(Object.keys(fields).filter(name=>relationEndpoints[name]).map(async name=>{const relation=relationEndpoints[name];const result=await api.get(relation.path);const data=Array.isArray(result.data)?result.data:result.data.items||result.data.data||[];return [name,data] as const}))}).then(entries=>setOptions(Object.fromEntries(entries||[]))).catch(e=>setError(apiErrorMessage(e))).finally(()=>setLoading(false))},[initial,mutation.path,mutation.schema]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(mutation.confirm&&!confirm(mutation.confirm))return;setSaving(true);setError("");try{let path=mutation.path;for(const name of pathFields(path))path=path.replace(`{${name}}`,values[name]);if(path.includes("{id}"))path=path.replace("{id}",String(initial?.id));const payload=buildPayload(schema,schemas,values);await api.request({url:path,method:mutation.method||"post",data:mutation.method==="delete"?undefined:payload});onSaved(`${mutation.label} completed successfully.`)}catch(e){setError(apiErrorMessage(e))}finally{setSaving(false)}};
 return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4" role="dialog" aria-modal="true"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="eyebrow">CCMS record</p><h2 className="text-2xl font-bold">{mutation.label}</h2></div><button type="button" onClick={onClose} className="secondary-button">Close</button></div>{error&&<div className="notice-error mt-4">{error}</div>}{loading?<p className="mt-6 text-sm text-slate-500">Loading form…</p>:<div className="form-grid mt-6">{Object.entries(properties).map(([name,raw])=>{const definition=resolve(raw,schemas);const required=(schema.required||[]).includes(name)||pathFields(mutation.path).includes(name);const enums=definition.enum;const relation=relationEndpoints[name];return <label className="form-field" key={name}><span>{human(name)}{required?" *":""}</span>{relation?<select required={required} value={values[name]||""} onChange={e=>setValues({...values,[name]:e.target.value})}><option value="">Select {human(name).toLowerCase()}</option>{(options[name]||[]).map(item=><option key={String(item[relation.value])} value={String(item[relation.value])}>{relation.text.map(key=>item[key]).filter(Boolean).join(" - ")}</option>)}</select>:enums?<select required={required} value={values[name]||""} onChange={e=>setValues({...values,[name]:e.target.value})}><option value="">Select {human(name).toLowerCase()}</option>{enums.map(item=><option key={String(item)}>{String(item)}</option>)}</select>:definition.type==="boolean"?<select required={required} value={values[name]||"false"} onChange={e=>setValues({...values,[name]:e.target.value})}><option value="true">Yes</option><option value="false">No</option></select>:name.includes("notes")||name.includes("remarks")||name.includes("description")||name.includes("address")?<textarea rows={3} required={required} value={values[name]||""} onChange={e=>setValues({...values,[name]:e.target.value})}/>:<input required={required} type={definition.format==="date"?"date":definition.format==="date-time"?"datetime-local":definition.format==="email"?"email":definition.type==="integer"||definition.type==="number"?"number":name.includes("password")?"password":"text"} value={values[name]||""} onChange={e=>setValues({...values,[name]:e.target.value})}/>}</label>})}</div>}<div className="mt-6 flex justify-end gap-3"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving||loading}>{saving?"Saving…":mutation.label}</button></div></form></div>;
}

export function RecordDetailsModal({title,row,onClose}:{title:string;row:Record<string,unknown>;onClose:()=>void}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><section className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">{title}</h2><button className="secondary-button" onClick={onClose}>Close</button></div><dl className="mt-6 grid gap-3 sm:grid-cols-2">{Object.entries(row).filter(([key])=>!/password|token|hash|cnic|passport|mobile|address|diagnosis|treatment|confidential|restricted/i.test(key)).map(([key,value])=><div className="rounded-lg bg-slate-50 p-3" key={key}><dt className="text-xs font-semibold uppercase text-slate-400">{human(key)}</dt><dd className="mt-1 break-words text-sm font-medium">{value===null||value===undefined||value===""?"-":typeof value==="object"?"Structured information":String(value)}</dd></div>)}</dl></section></div>}
