"""Add visitor management and detailed role permissions.

Revision ID: b11c4e7a903f
Revises: c10a7d4e2b91
Create Date: 2026-06-22
"""
from alembic import op
import sqlalchemy as sa

revision="b11c4e7a903f";down_revision="c10a7d4e2b91";branch_labels=None;depends_on=None
MODULE_ACTIONS={"dashboard":["view"],"children":["view","create","update","delete","export","import"],"children.documents":["view","upload","verify","delete","export"],"daily_attendance":["view","create","update","bulk_mark","delete","export"],"visitors":["view","create","update","delete","verify","block","export"],"child_visits":["view","create","update","delete","approve","reject","check_in","check_out","cancel","export"],"sponsors":["view","create","update","delete","export"],"sponsorships":["view","create","update","delete","cancel","export"],"accommodation":["view","create","update","delete","allocate","transfer","vacate","export"],"medical":["view","create","update","delete","export"],"education":["view","create","update","delete","export"],"case_management":["view","create","update","delete","close","export"],"reports":["view","export"],"imports":["view","upload","preview","commit"],"users":["view","create","update","deactivate","reset_password","assign_roles","export"],"roles":["view","create","update","delete","assign_permissions"],"audit_logs":["view","export"],"system_status":["view"]}
CATALOG=[f"{module}.{action}" for module,actions in MODULE_ACTIONS.items() for action in actions]
WARDEN={"dashboard.view","children.view","daily_attendance.view","daily_attendance.create","daily_attendance.update","daily_attendance.bulk_mark","child_visits.view","child_visits.create","child_visits.check_in","child_visits.check_out","visitors.view","accommodation.view"}
VIEW={name for name in CATALOG if name.endswith(".view")}
def defaults(role):
    if role=="Manager":return {name for name in CATALOG if not name.startswith(("users.","roles.","audit_logs."))}
    if role=="Data Entry Operator":return {name for name in CATALOG if name.split(".")[-1] in {"view","create","update","upload","preview","bulk_mark","check_in","check_out","cancel","export"} and not name.startswith(("users.","roles.","audit_logs.","system_status."))}
    if role=="Viewer":return VIEW|{"children.export","visitors.export","child_visits.export","sponsors.export","sponsorships.export","accommodation.export","medical.export","education.export","case_management.export","reports.export"}
    if role=="Warden":return WARDEN
    return set()
def upgrade():
    op.add_column("roles",sa.Column("is_system",sa.Boolean(),server_default=sa.false(),nullable=False))
    op.create_table("permissions",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("name",sa.String(150),nullable=False,unique=True),sa.Column("module",sa.String(100),nullable=False),sa.Column("action",sa.String(100),nullable=False),sa.Column("description",sa.String(255),nullable=True));op.create_index("ix_permissions_name","permissions",["name"],unique=True);op.create_index("ix_permissions_module","permissions",["module"])
    op.create_table("role_permissions",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("role_id",sa.Integer(),sa.ForeignKey("roles.id",ondelete="CASCADE"),nullable=False),sa.Column("permission_id",sa.Integer(),sa.ForeignKey("permissions.id",ondelete="CASCADE"),nullable=False),sa.UniqueConstraint("role_id","permission_id",name="uq_role_permissions_role_permission"));op.create_index("ix_role_permissions_role_id","role_permissions",["role_id"]);op.create_index("ix_role_permissions_permission_id","role_permissions",["permission_id"])
    op.create_table("visitors",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("visitor_code",sa.String(50),nullable=False,unique=True),sa.Column("full_name",sa.String(255),nullable=False),sa.Column("father_name",sa.String(255)),sa.Column("cnic_passport",sa.String(50)),sa.Column("mobile",sa.String(30)),sa.Column("alternate_mobile",sa.String(30)),sa.Column("relationship_to_child",sa.String(100),nullable=False),sa.Column("address",sa.Text()),sa.Column("district",sa.String(100)),sa.Column("province",sa.String(100)),sa.Column("photo_path",sa.Text()),sa.Column("is_verified",sa.Boolean(),server_default=sa.false(),nullable=False),sa.Column("verification_method",sa.String(100)),sa.Column("verified_by_user_id",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("status",sa.String(30),server_default="Pending Verification",nullable=False),sa.Column("remarks",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("created_by_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("updated_by_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("deleted_at",sa.DateTime(timezone=True)),sa.Column("deleted_by_user_id",sa.Integer(),sa.ForeignKey("users.id")),sa.CheckConstraint("status IN ('Active','Inactive','Blocked','Pending Verification')",name="ck_visitors_status"));op.create_index("ix_visitors_visitor_code","visitors",["visitor_code"],unique=True);op.create_index("ix_visitors_full_name","visitors",["full_name"]);op.create_index("ix_visitors_district","visitors",["district"]);op.create_index("ix_visitors_status_verified","visitors",["status","is_verified"])
    op.create_table("child_visits",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("visit_code",sa.String(50),nullable=False,unique=True),sa.Column("child_id",sa.Integer(),sa.ForeignKey("children.id",ondelete="RESTRICT"),nullable=False),sa.Column("visitor_id",sa.Integer(),sa.ForeignKey("visitors.id",ondelete="RESTRICT"),nullable=False),sa.Column("relationship_to_child",sa.String(100),nullable=False),sa.Column("visit_date",sa.Date(),nullable=False),sa.Column("check_in_time",sa.Time()),sa.Column("check_out_time",sa.Time()),sa.Column("meeting_purpose",sa.String(100),nullable=False),sa.Column("meeting_location",sa.String(100),nullable=False),sa.Column("supervised_by_user_id",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("approved_by_user_id",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("approval_status",sa.String(20),server_default="Pending",nullable=False),sa.Column("visit_status",sa.String(20),server_default="Scheduled",nullable=False),sa.Column("remarks",sa.Text()),sa.Column("safety_notes",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("created_by_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("updated_by_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.CheckConstraint("approval_status IN ('Pending','Approved','Rejected','Cancelled')",name="ck_child_visits_approval"),sa.CheckConstraint("visit_status IN ('Scheduled','Checked In','Completed','No Show','Cancelled')",name="ck_child_visits_status"),sa.CheckConstraint("check_out_time IS NULL OR check_in_time IS NULL OR check_out_time >= check_in_time",name="ck_child_visits_times"));op.create_index("ix_child_visits_visit_code","child_visits",["visit_code"],unique=True);op.create_index("ix_child_visits_child_id","child_visits",["child_id"]);op.create_index("ix_child_visits_visitor_id","child_visits",["visitor_id"]);op.create_index("ix_child_visits_visit_date","child_visits",["visit_date"]);op.create_index("ix_child_visits_date_status","child_visits",["visit_date","visit_status"])
    bind=op.get_bind();roles=sa.table("roles",sa.column("id",sa.Integer),sa.column("name",sa.String),sa.column("is_system",sa.Boolean));permissions=sa.table("permissions",sa.column("id",sa.Integer),sa.column("name",sa.String),sa.column("module",sa.String),sa.column("action",sa.String),sa.column("description",sa.String));role_permissions=sa.table("role_permissions",sa.column("role_id",sa.Integer),sa.column("permission_id",sa.Integer))
    bind.execute(roles.update().where(roles.c.name.in_(["Admin","Manager","Data Entry Operator","Viewer"])).values(is_system=True))
    if bind.execute(sa.select(roles.c.id).where(roles.c.name=="Warden")).scalar() is None:bind.execute(roles.insert().values(name="Warden",is_system=True))
    bind.execute(permissions.insert(),[{"name":name,"module":name.rsplit(".",1)[0],"action":name.rsplit(".",1)[1],"description":name.replace("."," ").replace("_"," ").title()} for name in CATALOG])
    role_map=dict(bind.execute(sa.select(roles.c.name,roles.c.id)).all());permission_map=dict(bind.execute(sa.select(permissions.c.name,permissions.c.id)).all());links=[{"role_id":role_map[role],"permission_id":permission_map[name]} for role in ("Manager","Data Entry Operator","Viewer","Warden") if role in role_map for name in defaults(role)];bind.execute(role_permissions.insert(),links)
def downgrade():
    op.drop_table("child_visits");op.drop_table("visitors");op.drop_table("role_permissions");op.drop_table("permissions");op.drop_column("roles","is_system")
