"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, Baby, BedDouble, BriefcaseMedical, GraduationCap, HandHeart, ShieldAlert, UsersRound } from "lucide-react";
import { api, apiErrorMessage } from "@/lib/api";
import type { DashboardSummaryCard, ExecutiveDashboardResponse } from "@/types/dashboard";

export default function Dashboard(){const [data,setData]=useState<ExecutiveDashboardResponse|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  useEffect(()=>{api.get<ExecutiveDashboardResponse>("/dashboard/executive").then(r=>setData(r.data)).catch(e=>setError(apiErrorMessage(e))).finally(()=>setLoading(false));},[]);
  const cards=useMemo<DashboardSummaryCard[]>(()=>data?[
    {label:"Total Children",value:data.children_summary.total_children},{label:"Active Children",value:data.children_summary.active_children,tone:"success"},{label:"Active Sponsors",value:data.sponsorship_summary.active_sponsors},{label:"Occupancy",value:`${data.accommodation_summary.occupancy_percentage||0}%`},{label:"Active Students",value:data.education_summary.active_students},{label:"Active Medications",value:data.medical_summary.active_medications},{label:"Open Cases",value:data.case_management_summary.open_cases},{label:"Critical Alerts",value:(data.alerts_summary.critical_incidents||0)+(data.alerts_summary.critical_risk_children||0),tone:"danger"},{label:"Pending Actions",value:Object.values(data.pending_actions_summary).reduce((sum,value)=>sum+Number(value||0),0)}]:[],[data]);
  const icons=[Baby,UsersRound,HandHeart,BedDouble,GraduationCap,BriefcaseMedical,Activity,ShieldAlert,Activity];
  if(loading)return <DashboardLoading/>;
  if(error)return <section className="empty-card"><ShieldAlert className="text-red-500"/><h2>Dashboard unavailable</h2><p>{error}</p><button onClick={()=>location.reload()} className="primary-button">Try again</button></section>;
  if(!data)return <section className="empty-card"><h2>No dashboard data yet</h2><p>Operational summaries will appear after records are added.</p></section>;
  return <div className="space-y-8"><div><p className="eyebrow">Executive overview</p><h2 className="page-title">Dashboard</h2><p className="page-subtitle">A concise view of care operations and actions requiring attention.</p></div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map((card,index)=>{const Icon=icons[index];return <article key={card.label} className="metric-card"><div className={`metric-icon ${card.tone||""}`}><Icon size={20}/></div><div><p>{card.label}</p><strong>{card.value}</strong></div></article>})}</section><section className="grid gap-6 xl:grid-cols-2"><Summary title="Alerts summary" values={data.alerts_summary} danger/><Summary title="Pending actions" values={data.pending_actions_summary}/></section></div>}
function Summary({title,values,danger=false}:{title:string;values:Record<string,number>;danger?:boolean}){const entries=Object.entries(values);return <article className="panel"><div className="panel-title"><h3>{title}</h3><span className={danger?"badge-danger":"badge"}>{entries.reduce((s,[,v])=>s+Number(v||0),0)} total</span></div>{entries.length?<div className="divide-y divide-slate-100">{entries.map(([key,value])=><div key={key} className="flex items-center justify-between py-3 text-sm"><span className="text-slate-600">{key.replaceAll("_"," ").replace(/\b\w/g,l=>l.toUpperCase())}</span><strong className="text-slate-900">{value}</strong></div>)}</div>:<p className="text-sm text-slate-500">Nothing to show.</p>}</article>}
function DashboardLoading(){return <div className="space-y-6"><div className="h-8 w-48 animate-pulse rounded bg-slate-200"/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({length:9}).map((_,i)=><div key={i} className="h-28 animate-pulse rounded-xl bg-slate-200"/>)}</div></div>}
